USE [master]
GO
/****** Object:  Database [Gestao]    Script Date: 08/02/2023 21:42:44 ******/
CREATE DATABASE [Gestao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gestao', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\Gestao.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Gestao_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\Gestao_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Gestao] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gestao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Gestao] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Gestao] SET ARITHABORT OFF 
GO
ALTER DATABASE [Gestao] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Gestao] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Gestao] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Gestao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Gestao] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Gestao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Gestao] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Gestao] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Gestao] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Gestao] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Gestao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Gestao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Gestao] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Gestao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Gestao] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Gestao] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Gestao] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Gestao] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Gestao] SET  MULTI_USER 
GO
ALTER DATABASE [Gestao] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Gestao] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Gestao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Gestao] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Gestao] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Gestao] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Gestao] SET QUERY_STORE = OFF
GO
USE [Gestao]
GO
/****** Object:  Table [dbo].[GrupoUsuario]    Script Date: 08/02/2023 21:42:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GrupoUsuario](
	[ID] [int] NOT NULL,
	[GrupoUsuario] [nchar](10) NOT NULL,
 CONSTRAINT [PK_GrupoUsuario] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao]    Script Date: 08/02/2023 21:42:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao](
	[ID] [int] NOT NULL,
	[DESCRICAO] [int] NOT NULL,
 CONSTRAINT [PK_Permissao] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSAOGRUPOUSUARIO]    Script Date: 08/02/2023 21:42:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSAOGRUPOUSUARIO](
	[ID_PERMISSAO] [int] NOT NULL,
	[ID_GRUPOUSUARIO] [int] NOT NULL,
 CONSTRAINT [PK_PERMISSAOGRUPOUSUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_PERMISSAO] ASC,
	[ID_GRUPOUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 08/02/2023 21:42:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](150) NULL,
	[NOMEUSUARIO] [varchar](150) NULL,
	[CPF] [varchar](15) NULL,
	[EMAIL] [varchar](150) NULL,
	[SENHA] [varchar](50) NULL,
	[ATIVO] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIOGRUPOUSUARIO]    Script Date: 08/02/2023 21:42:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOGRUPOUSUARIO](
	[ID_USUARIO] [int] NOT NULL,
	[ID_GRUPOUSUARIO] [int] NOT NULL,
 CONSTRAINT [PK_USUARIOGRUPOUSUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC,
	[ID_GRUPOUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISSAOGRUPOUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK_PERMISSAOGRUPOUSUARIO_GrupoUsuario] FOREIGN KEY([ID_GRUPOUSUARIO])
REFERENCES [dbo].[GrupoUsuario] ([ID])
GO
ALTER TABLE [dbo].[PERMISSAOGRUPOUSUARIO] CHECK CONSTRAINT [FK_PERMISSAOGRUPOUSUARIO_GrupoUsuario]
GO
ALTER TABLE [dbo].[PERMISSAOGRUPOUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK_PERMISSAOGRUPOUSUARIO_Permissao] FOREIGN KEY([ID_PERMISSAO])
REFERENCES [dbo].[Permissao] ([ID])
GO
ALTER TABLE [dbo].[PERMISSAOGRUPOUSUARIO] CHECK CONSTRAINT [FK_PERMISSAOGRUPOUSUARIO_Permissao]
GO
ALTER TABLE [dbo].[USUARIOGRUPOUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOGRUPOUSUARIO_GrupoUsuario] FOREIGN KEY([ID_GRUPOUSUARIO])
REFERENCES [dbo].[GrupoUsuario] ([ID])
GO
ALTER TABLE [dbo].[USUARIOGRUPOUSUARIO] CHECK CONSTRAINT [FK_USUARIOGRUPOUSUARIO_GrupoUsuario]
GO
ALTER TABLE [dbo].[USUARIOGRUPOUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOGRUPOUSUARIO_Usuario] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[Usuario] ([ID])
GO
ALTER TABLE [dbo].[USUARIOGRUPOUSUARIO] CHECK CONSTRAINT [FK_USUARIOGRUPOUSUARIO_Usuario]
GO
USE [master]
GO
ALTER DATABASE [Gestao] SET  READ_WRITE 
GO
